(function(g){var window=this;'use strict';var I4=function(a){a.ra("cardstatechange",a.Ik()&&a.Po()?1:0)},J4=function(a,b){var c=g.Ta(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},seb=function(a){var b=g.zn(a);
a=g.Cn(a);return new g.on(b.x,b.y,a.width,a.height)},M4=function(a){a=g.Ya(a);
delete K4[a];g.id(K4)&&L4&&L4.stop()},ueb=function(){L4||(L4=new g.lq(function(){teb()},20));
var a=L4;a.isActive()||a.start()},teb=function(){var a=g.cb();
g.Zc(K4,function(b){veb(b,a)});
g.id(K4)||ueb()},N4=function(a,b,c,d){g.Fq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.K=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.J=0;this.C=null},veb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.C);a.C=b;web(a,a.progress);1==a.progress?(a.j=0,M4(a),a.onFinish(),a.ir()):a.qd()&&a.ZJ()},web=function(a,b){"function"===typeof a.D&&(b=a.D(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.K[c]-a.u[c])*b+a.u[c]},xeb=function(a,b){g.ub.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},O4=function(a,b,c,d,e){N4.call(this,b,c,d,e);
this.element=a},yeb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
O4.call(this,a,b,c,d,e)},zeb=function(a){return Math.pow(a,3)},Aeb=function(a){return 3*a*a-2*a*a*a},Beb=function(a){g.D.call(this);
this.u=a||window;this.j=[]},P4=function(a){return a.baseUrl||null},Q4=function(a,b){return g.xo(g.Hm(a,b),function(c){return!!c})},Ceb=function(a,b,c){function d(aa){var la=aa.hovercardButton;
if(!la)return null;la=la.subscribeButtonRenderer;if(!la)return null;var ca=f(la.unsubscribedButtonText),Da=f(la.subscribedButtonText);if(la.subscribed){var W=f(la.subscriberCountWithUnsubscribeText);var Ua=f(la.subscriberCountText)}else W=f(la.subscriberCountText),Ua=f(la.subscriberCountWithSubscribeText);var t=null;if(aa.signinEndpoint){t=J4(aa,"signinEndpoint","webNavigationEndpointData","url");if(!t){var Q,jb;t=null==(jb=g.S(null==(Q=la.signInEndpoint)?void 0:Q.commandMetadata,g.C3))?void 0:jb.url}if(!t)return null}return ca&&
(Da||t)?{subscribed:la.subscribed,subscribeText:ca,subscribeCount:W,unsubscribeText:Da,unsubscribeCount:Ua,enabled:la.enabled,signinUrl:t,classic:aa.useClassicSubscribeButton}:null}
function e(aa){if(aa){var la=[],ca=aa.videoId;ca&&la.push("v="+ca);(ca=aa.playlistId)&&la.push("list="+ca);(aa=aa.startTimeSeconds)&&la.push("t="+aa);return"/watch?"+la.join("&")}}
function f(aa){if(!aa)return null;var la=aa.simpleText;return la?la:aa.runs?g.Hm(aa.runs,function(ca){return ca.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,u=null,y=null,A=!1,F=null,M=null,K=null,G=null,T=null,Z=null;if("VIDEO"===h)g.S(l,g.xO)?m=g.S(l,g.xO).url:(Z=g.S(l,g.wO),m=e(Z)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.S(l,g.xO)?m=g.S(l,g.xO).url:(Z=g.S(l,g.wO),m=e(Z)),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"===
h){if(A=J4(l,"browseEndpoint","browseId"))y=A,m="/channel/"+y;n=!1;q="new";(A=!!b.isSubscribe)?F=d(b):M=f(b.subscribersText)}else"WEBSITE"===h?((K=J4(l,"urlEndpoint","url"))&&(m=K),n=!0,q="new",K=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(T=f(b.additionalFeesText)),(n=J4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=J4(b,"title","accessibility","accessibilityData","label");var ka=b.endpoint?b.endpoint.clickTrackingParams:null,
ua="";if(b.metadata){var oa=f(b.metadata);oa&&(ua=oa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ua,callToAction:f(b.callToAction),xU:b.image,iconUrl:K,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,ZC:p,playlistLength:u,channelId:y,subscribeButton:F,subscribersText:M,isSubscribe:A,vu:m||null,x5:n,sessionData:ka?{itct:ka}:null,p$:q,AB:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:Q4(b.impressionUrls||[],P4),m5:Q4(b.hovercardShowUrls||[],P4),clickUrls:Q4(l.loggingUrls||[],P4),visualElement:g.KG(b.trackingParams),productPrice:G,additionalFeesText:T,watchEndpoint:Z||null}},Deb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:Q4(a.impressionUrls||[],P4),elements:Q4(a.elements||[],function(d,e){return Ceb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.KG(a.trackingParams));return c},Eeb=function(a){g.XT.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.K=[];this.ea=!0;this.J=0;a=a.W();this.V=g.HM(a)||"profilepage"===a.Na;this.events=new g.pK(this);g.H(this,this.events);this.events.T(this.player,g.jG("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.kG("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Kb);this.events.T(window,"focus",this.W8);this.load();var b=g.af("STYLE");(g.Oe("HEAD")[0]||document.body).appendChild(b);g.rb(this,
function(){g.jf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Feb=function(a){return a.player.getVideoData().Ed?"current":a.V?"new":"current"},R4=function(a){return"creator-endscreen-editor"===a.player.W().playerStyle},Geb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Deb(f,Feb(a))));S4(a,f)},
urlParams:{v:c},withCredentials:!0};a.V&&(c.urlParams.ptype="embedded");var d=b.wx;d&&(c.postParams={ad_tracking:d});if(b=g.hza(b))if(b=g.ae(b),b=g.Zd(b))a.B=g.Az(b,c)},S4=function(a,b,c){c=void 0===c?!0:c;
a.player.Ie("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.v(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&Heb(a);c=[];d=new g.hG(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.W().u||(a.u=new g.X({G:"div",S:"ytp-ce-shadow"}),g.$S(a.player,a.u.element,4),a.C=new g.CR(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Ieb(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.$S(a.player,f.element,4);var h=new g.hG(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Jeb(a,f,e)}else g.OF(new g.XA("buildEndscreenElement null",
e))}a.player.gf(c);a.Kb()}},Heb=function(a){var b=g.MG(),c=g.NG();
c&&b&&a.endscreen.visualElement&&g.fz(g.oQ)(void 0,c,b,a.endscreen.visualElement)},Ieb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Ma:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.AB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-covering-image",Y:T4(b)},{G:"div",S:"ytp-ce-covering-shadow-top"},{G:"a",S:"ytp-ce-covering-overlay",Y:{href:U4(a,b.vu),tabindex:"-1"},X:[{G:"div",Ma:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.Jq(b.title||"")},Aa:b.title},{G:"div",S:b.ZC?"ytp-ce-live-video-duration":"ytp-ce-video-duration",Aa:b.videoDuration||
void 0}]}]};c=new g.X(a);break;case "PLAYLIST":a={G:"div",Ma:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.AB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-covering-image",Y:T4(b)},{G:"div",S:"ytp-ce-covering-shadow-top"},{G:"a",S:"ytp-ce-covering-overlay",Y:{href:U4(a,b.vu),tabindex:"-1"},X:[{G:"div",Ma:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.Jq(b.title||"")},Aa:b.title},{G:"div",S:"ytp-ce-playlist-count",X:[{G:"div",S:"ytp-ce-playlist-icon"},
{G:"div",S:"ytp-ce-playlist-count-text",Aa:b.playlistLength||void 0}]}]}]};c=new g.X(a);break;case "CHANNEL":c={G:"div",Ma:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.AB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",X:[{G:"div",
S:"ytp-ce-expanding-overlay-body",X:[{G:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"a",Ma:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:U4(a,b.vu),target:"_blank",tabindex:"-1",dir:g.Jq(b.title||"")},Aa:b.title},b.subscribeButton?{G:"div",S:"ytp-ce-subscribe-container",X:[{G:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",S:"ytp-ce-channel-subscribers-text",Aa:b.subscribersText}:"",b.metadata?{G:"div",Ma:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
Aa:b.metadata}:""]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:T4(b)}]};c=new g.X(c);var d=g.Pe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.tq(d,"ytp-ce-subscribe-button");if(a.player.W().u){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.NU(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ma:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.AB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",X:[{G:"div",S:"ytp-ce-expanding-overlay-body",X:[{G:"div",
S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"div",S:"ytp-ce-website-title",Y:{dir:g.Jq(b.title||"")},Aa:b.title},{G:"div",S:"ytp-ce-website-metadata",Aa:b.metadata},{G:"a",Ma:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:U4(a,b.vu),target:"_blank",tabindex:"-1"},Aa:b.callToAction}]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:T4(b)},{G:"div",S:"ytp-ce-expanding-icon",Y:Keb(b.iconUrl)}]};c=new g.X(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",S:"ytp-ce-merchandise-price-container",
X:[{G:"div",S:"ytp-ce-merchandise-price",Aa:b.productPrice}]},b.additionalFeesText&&c.X.push({G:"div",S:"ytp-ce-merchandise-additional-fees",Aa:b.additionalFeesText})),a={G:"div",Ma:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.AB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",
X:[{G:"div",S:"ytp-ce-expanding-overlay-body",X:[{G:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"div",S:"ytp-ce-merchandise-title",Y:{dir:g.Jq(b.title||"")},Aa:b.title},c,{G:"div",S:"ytp-ce-merchandise-metadata",Aa:b.metadata},{G:"a",Ma:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:U4(a,b.vu),target:"_blank",tabindex:"-1"},Aa:b.callToAction}]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:T4(b)},{G:"div",S:"ytp-ce-merchandise-invideo-cta-container",X:[{G:"div",S:"ytp-ce-merchandise-invideo-cta",
Aa:b.callToAction||void 0}]}]},c=new g.X(a)}b.isPlaceholder&&g.tq(c.element,"ytp-ce-placeholder");return c},T4=function(a){if(a.xU)var b=a.xU.thumbnails;
return Keb(b?b[b.length-1].url:null)},Keb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Jeb=function(a,b,c){function d(m){m&&(b.Ta("blur",function(){"none"!=m.style.display&&a.ea&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.J+=m;0<a.J?(g.tq(b.element,"ytp-ce-force-expand"),V4(a,c.id,!0)):(g.vq(b.element,"ytp-ce-force-expand"),g.vq(b.element,"ytp-ce-element-hover"),V4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ta("mouseenter",function(){Leb(a,b,c)});
b.Ta("mouseleave",function(){Meb(a,b,c)});
a.player.W().u||b.Ta("click",function(){g.tq(b.element,"ytp-ce-element-hover")});
b.Ta("click",function(m){Neb(a,c,m)});
b.Ta("keypress",function(m){Neb(a,c,m)});
b.Ta("focus",function(){Leb(a,b,c)});
b.Ta("blur",function(){Meb(a,b,c)});
b.Ta("touchstart",function(){Leb(a,b,c)});
var l=g.Re("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){g.XP?m.stopPropagation():(m=m||window.event,m.cancelBubble=!0,m.stopPropagation&&m.stopPropagation());g.vq(b.element,"ytp-ce-element-hover");g.vq(b.element,"ytp-ce-force-expand")});
b.Ta("keydown",function(m){a.ea=9===m.keyCode&&!m.shiftKey});
d(g.Re("ytp-sb-subscribe",b.element));d(g.Re("ytp-sb-unsubscribe",b.element));b.Ta("focus",f);b.Ta("blur",h)},Neb=function(a,b,c){if(b.vu&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.sq(d,"ytp-ce-element");){g.sq(d,"subscribe-label")&&Oeb(a,b);
if(g.sq(d,"ytp-ce-channel-subscribe"))return;d=g.kf(d)}if(!d||g.sq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Meb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.p$)Oeb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.ae(U4(a,b.vu)),g.zP(g.Zd(c),void 0,b.sessionData);else{var e=g.XM(a.player.W())||a.player.getVideoData().Ed,f=function(){var h=U4(a,b.vu),l=b.sessionData,m=b.watchEndpoint,n=g.lz(h);e&&n&&(n.v||n.list)?a.player.po(n.v,
l,n.list,!1,void 0,m||void 0):g.Pza(h,l)};
Oeb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},U4=function(a,b){a=a.player.W();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.dN(a)+b}else return"";return b},Leb=function(a,b,c){g.sq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.tq(b.element,"ytp-ce-element-hover"):a.player.W().u?(new g.lq(function(){g.tq(b.element,"ytp-ce-element-hover")},200)).start():g.tq(b.element,"ytp-ce-element-hover"),W4(a,c.m5),V4(a,c.id,!0))},Meb=function(a,b,c){g.vq(b.element,"ytp-ce-element-hover");
g.vq(b.element,"ytp-ce-force-expand");V4(a,c.id,!1)},V4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.v(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.xq(a.j[e].element,"ytp-ce-element-shadow-show",c)},W4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||R4(a))c&&c();else{b=Peb(a,b);var e=0,f=!1,h=new g.lq(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.RC(b[a],d)}},Oeb=function(a,b,c){W4(a,b.clickUrls,c);
(a=g.NG())&&b.x5&&g.uQ(a,b.visualElement)},Peb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Qeb(b[d],c));return a},Qeb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Reb=function(a){return"string"===typeof a?a:""},X4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Seb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},Y4=function(a){return a.value?a.value:null},Z4=function(a){if(!a)return null;
var b=g.ae(Reb(a.value));b=g.Zd(b);if(!b)return null;var c=X4(a.target,Teb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Seb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Ueb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Xeb=function(a){if(!a)return null;
var b=X4(a.type,Veb),c=X4(a.trigger,Web);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=Z4(a?a:null);return b?new Ueb(b,c,a):null},Yeb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Zeb=function(a,b){return g.Bb(a.action,b)},$eb=function(a,b){this.context=a;
this.j=b},afb=function(a){return a.customMessage?$4("div","iv-card-message",a.customMessage):""},a5=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",S:"iv-card-image",Y:{style:a},X:c}},bfb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.v(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push($4("li","",c.value));return{G:"ul",S:"iv-card-meta-info",X:b}},$4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Jq(c);return{G:a,Y:b,Aa:c}},cfb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.IB&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.IB+");");c.dir=g.Jq(a.customMessage);var d=[{G:"span",Aa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",S:"iv-card-link-icon"}));return{G:"div",Ma:b,Y:c,X:d}},b5=function(a,b,c,d){if(d){b=g.v(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.bj.click,5)}},dfb=function(a,b){this.merchant=a;
this.price=b},efb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},ffb=function(a,b){return b?b:efb(a)?"current":"new"},c5=function(a,b){g.D.call(this);
var c=this;this.element=a;this.context=b;this.xb=!1;this.fb=new Map;this.kb=new Map;this.context.I.addEventListener(g.jG("annotations_module"),function(d){(d=c.fb.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.kG("annotations_module"),function(d){(d=c.kb.get(d))&&d.apply(c)})},d5=function(a,b,c,d,e,f,h){a.context.j.Ta(b,"click",function(l){a.aK(c,d,e,f||[],h||0,l)});
a.context.j.Ta(b,"touchstart",function(){a.xb=!1});
a.context.j.Ta(b,"touchmove",function(){a.xb=!0})},gfb=function(a){var b;
return(null==(b=g.S(a,g.xO))?0:b.url)?g.S(a,g.xO).url:(a=g.S(a,g.wO))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},e5=function(a,b,c){return{SV:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
qZ:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
nJ:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},hfb=function(a,b,c){c5.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Oa=this.Sb=this.B=this.isInitialized=!1;this.cards=[];this.Jb=this.V=this.Na=this.D=this.Ya=this.j=null;this.oa=[];this.qa=this.K=this.xg=this.Fa=null;this.J=0;this.Ga=new g.lq(function(){},c.Z.Ki?4E3:3E3);
g.H(this,this.Ga);this.rb=new g.lq(function(){});
g.H(this,this.rb);this.Ba=new $eb(c,function(e,f,h,l,m,n){d5(d,e,f,h,l,m,n)});
this.ea=new g.X({G:"div",S:"iv-drawer",Y:{id:"iv-drawer"},X:[{G:"div",S:"iv-drawer-header",Y:{"aria-role":"heading"},X:[{G:"span",S:"iv-drawer-header-text"},{G:"button",Ma:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",S:"iv-drawer-content"}]});g.H(this,this.ea);this.C=this.ea.element;this.ob=new g.CR(this.ea,330);g.H(this,this.ob);this.Zb=g.Re("iv-drawer-header-text",this.C);this.u=g.Re("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Sb&&f5(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Sb=d.B)&&g5(d)});
this.Va=new g.pK(this);g.H(this,this.Va);this.I.addEventListener("videodatachange",this.qt.bind(this))},ifb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){f5(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){g5(a)});
var c=b.headerText;g.mf(a.Zb,c);a.V&&a.V.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.KG(b.trackingParams);a.K=g.KG(b.closeTrackingParams);a.xg=g.KG(b.iconTrackingParams)},jfb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J,d=a.I.W().experiments.sb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.pG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,bj:{},Qo:null,zl:e.trackingParams?g.KG(e.trackingParams):null,xg:f&&f.trackingParams?g.KG(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
IB:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};h5(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.pG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:i5(a,c,b,f),sponsored:!1,bj:e5(f,e,f.command),Qo:f.trackingParams?g.KG(f.trackingParams):null,zl:e.trackingParams?g.KG(e.trackingParams):null,xg:l&&l.trackingParams?g.KG(l.trackingParams):null,imageUrl:j5(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.pG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,IB:null,title:f.title?g.pG(f.title):"",customMessage:f.callToAction?g.pG(f.callToAction):"",url:g.S(f.command,g.xO).url?Z4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(f.command,g.xO).url}):null,onClickCommand:null};h5(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.pG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:i5(a,c,b,e),sponsored:!1,bj:e5(e,f,e.endpoint),Qo:e.trackingParams?g.KG(e.trackingParams):null,zl:f.trackingParams?g.KG(f.trackingParams):null,xg:l&&l.trackingParams?g.KG(l.trackingParams):null,channelId:g.S(e.endpoint,g.B3).browseId,customMessage:e.customText?g.pG(e.customText):null,eY:j5(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.pG(e.channelName):"",metaInfo:[e.subscriberCountText?g.pG(e.subscriberCountText):""],url:Z4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(e.endpoint,g.B3).canonicalBaseUrl?g.S(e.endpoint,g.B3).canonicalBaseUrl:"/channel/"+g.S(e.endpoint,g.B3).browseId}),onClickCommand:null};h5(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.pG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:i5(a,c,b,e),sponsored:!1,bj:e5(e,f,e.action),Qo:e.trackingParams?g.KG(e.trackingParams):null,zl:f.trackingParams?g.KG(f.trackingParams):null,xg:l&&l.trackingParams?g.KG(l.trackingParams):null,RE:j5(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.pG(e.customMessage):null,playlistVideoCount:g.pG(e.playlistVideoCount),title:e.playlistTitle?g.pG(e.playlistTitle):"",metaInfo:[e.channelName?g.pG(e.channelName):
"",e.videoCountText?g.pG(e.videoCountText):""],url:Z4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:gfb(e.action)}),onClickCommand:null};h5(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.pG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:i5(a,c,b,e),sponsored:!1,bj:e5(e,f,e.action),Qo:e.trackingParams?g.KG(e.trackingParams):null,zl:f.trackingParams?g.KG(f.trackingParams):null,xg:l&&l.trackingParams?g.KG(l.trackingParams):null,RE:j5(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.pG(e.lengthString):null,customMessage:e.customMessage?g.pG(e.customMessage):null,title:e.videoTitle?g.pG(e.videoTitle):"",metaInfo:[e.channelName?g.pG(e.channelName):
"",e.viewCountText?g.pG(e.viewCountText):""],isLiveNow:!!e.badge,url:Z4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:gfb(e.action)}),onClickCommand:null};h5(a,b)}}}}}a.J++},j5=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},i5=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},lfb=function(a,b){if(b=kfb(a,b))b===a.j&&(a.j=null),a.I.removeCueRange(b.qg.id),g.jf(b.GL),g.Hb(a.cards,b),a.PF(),k5(a)},f5=function(a,b,c){if(!a.B){a.ob.show();
a.Ya=new g.lq(function(){g.tq(a.context.I.getRootNode(),g.AX.IV_DRAWER_OPEN)},0);
a.Ya.start();a.Va.T(a.u,"mousewheel",function(h){a.Ga.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.NG();d&&a.Fa&&a.K&&g.sQ(d,[a.Fa,a.K]);b={TRIGGER_TYPE:b};for(var e=g.v(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.EW||(f.EW=!0,mfb(a.context.logger,f.qg.bj.SV,b)),d&&g.sQ(d,[f.qg.Qo]);I4(a.I);c&&(a.D=new g.lq(function(){a.Na=a.V;a.Jb.focus()},330),a.D.start())}},g5=function(a){a.B&&(a.ob.hide(),g.GA(a.Va),g.vq(a.context.I.getRootNode(),g.AX.IV_DRAWER_OPEN),a.B=!1,I4(a.I),a.D&&a.D.stop(),a.D=new g.lq(function(){a.Na&&(a.Na.focus(),a.Na=null)},330),a.D.start())},ofb=function(a){g.uq(a.Ab(),
[g.AX.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.$S(a.I,a.C,5);nfb(a);a.V=g.Re("ytp-cards-button",a.I.getRootNode());a.Jb=g.Re("iv-drawer-close-button",a.C);a.isInitialized=!0},nfb=function(a){var b=g.Re("iv-drawer-close-button",a.C);
a.context.j.Ta(b,"click",a.B3,a);a.context.j.Ta(a.u,"touchend",function(){a.Ga.start()});
a.context.j.Ta(a.u,"scroll",a.T3,a);a.context.u.subscribe("onHideControls",function(){a.Oa=!0});
a.context.u.subscribe("onShowControls",function(){a.Oa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Oa=g.sq(a.I.getRootNode(),"ytp-autohide")});
a.oa.push(g.hD("iv-button-shown",a.I5,a));a.oa.push(g.hD("iv-button-hidden",a.H5,a));a.oa.push(g.hD("iv-teaser-shown",a.Z_,a));a.oa.push(g.hD("iv-teaser-hidden",a.J5,a));a.oa.push(g.hD("iv-teaser-clicked",a.Y_,a))},pfb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.S(b.onClickCommand,g.ebb))?void 0:c.targetId)?(a.qa=b,!0):!1},qfb=function(a,b){a.qa=b;
var c=a.I.getVideoData();if(!c)return!1;c=a.I.N("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.zxa(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.S(h[0],g.QPa))?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},
h5=function(a,b){if(!pfb(a,b)||qfb(a,b)){var c=rfb(a,b);
if(c){var d={qg:b,GL:c.element,EW:!1};if(!b.onClickCommand){a.isInitialized||ofb(a);lfb(a,b.id);var e=sfb(a,d);g.Ob(a.cards,e,0,d);c.Ja(a.u,e);a.PF()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,k5(a),tfb(a,d),f5(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&ufb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){ufb(a,d)}),k5(a))}}},rfb=function(a,b){switch(b.type){case "simple":a=a.Ba;
var c=b.displayDomain?{G:"div",S:"iv-card-image-text",Aa:b.displayDomain}:void 0;var d=cfb(b);c={G:"div",Ma:["iv-card"],X:[{G:"a",S:"iv-click-target",Y:{href:b.url?Y4(b.url)||"":""},X:[a5(b.imageUrl,c),{G:"div",S:"iv-card-content",X:[$4("h2",void 0,b.title),d]}]}]};c=new g.X(c);b5(a,g.Qe("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ba;c={G:"div",Ma:["iv-card","iv-card-channel"],X:[{G:"a",Ma:["iv-click-target"],Y:{href:Y4(b.url)||"","data-ytid":b.channelId},X:[a5(b.eY),{G:"div",
S:"iv-card-content",X:[afb(b),{G:"h2",S:"iv-card-primary-link",Aa:b.title},bfb(b)]}]}]};c=new g.X(c);b5(a,g.Qe("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ba;c={G:"div",Ma:["iv-card","iv-card-playlist"],X:[{G:"a",S:"iv-click-target",Y:{href:Y4(b.url)||""},X:[a5(b.RE,{G:"div",S:"iv-card-image-overlay",X:[{G:"span",S:"iv-card-playlist-video-count",Aa:b.playlistVideoCount}]}),{G:"div",S:"iv-card-content",X:[afb(b),$4("h2","iv-card-primary-link",b.title),bfb(b)]}]}]};c=new g.X(c);
b5(a,g.Qe("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ba;var e=0!=b.offers.length;c=["iv-card"];d="";var f=cfb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",S:"iv-card-offer-price",Aa:f.price}),f.merchant&&e.push({G:"div",S:"iv-card-offer-merchant",Aa:f.merchant}),f={G:"div",X:e});e=b.url?Y4(b.url)||"":"";c={G:"div",Ma:c,Y:{tabindex:"0"},X:[{G:"a",Ma:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",S:"iv-card-content",X:[b.sponsored?{G:"div",S:"iv-card-sponsored",X:["Sponsored",{G:"div",S:"iv-ad-info-container",X:[{G:"div",S:"iv-ad-info",Aa:"{{adInfo}}"},{G:"div",S:"iv-ad-info-icon-container",X:[{G:"div",S:"iv-ad-info-icon"},{G:"div",S:"iv-ad-info-callout"}]}]}]}:"",{G:"a",S:"iv-click-target",Y:{href:e},X:[$4("h2",d,b.title),f]}]}]};c=new g.X(c);d=g.af("span");g.mf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.qe(d,"adInfo");b5(a,g.Qe("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ba;d=b.videoDuration?{G:"span",S:"iv-card-video-duration",Aa:b.videoDuration}:void 0;f=b.isLiveNow?{G:"span",Ma:["yt-badge","yt-badge-live"],Aa:"LIVE NOW"}:null;e={G:"div",Ma:["iv-card","iv-card-video"],X:[{G:"a",S:"iv-click-target",Y:{href:(null==(c=b.url)?void 0:Y4(c))||""},X:[a5(b.RE,d),{G:"div",S:"iv-card-content",X:[afb(b),$4("h2","iv-card-primary-link",b.title),bfb(b),f]}]}]};c=new g.X(e);b5(a,g.Qe("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},sfb=function(a,b){if(0===a.cards.length)return 0;
a=g.Cb(a.cards,function(c){return b.qg.startMs>c.qg.startMs||b.qg.startMs===c.qg.startMs&&b.qg.timestamp>=c.qg.timestamp?!0:!1});
return-1===a?0:a+1},vfb=function(a){if(a.j)return"productListing"===a.j.qg.type;
if(a.I.N("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.Im(a.cards,function(c){return"productListing"===c.qg.type})}return g.Im(a.cards,function(c){return"productListing"===c.qg.type})},k5=function(a){g.xq(a.I.getRootNode(),"ytp-cards-shopping-active",vfb(a))},ufb=function(a,b){if(!g.sq(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.NG(),d=a.j?a.j.qg.xg:a.xg;
c&&d&&g.tQ(c,[d]);a.j=b;k5(a)}(c=a.isInitialized&&"none"==a.Ab().style.display)||(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=!(1===c||3===c||d));c||b.qg.teaserDurationMs&&a.I.mA(!0,{teaserText:b.qg.teaserText,durationMs:b.qg.teaserDurationMs,onClickCommand:b.qg.onClickCommand});a.rb.isActive()||((!a.B||!a.Ga.isActive()&&a.Oa)&&tfb(a,b),a.rb.start(910+b.qg.teaserDurationMs))}},tfb=function(a,b){a.ea.Fb?(b=new N4([0,
a.u.scrollTop],[0,b.GL.offsetTop],600,Aeb),a.context.B.Ta(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ta(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.dR(a.ea,!0),a.u.scrollTop=b.GL.offsetTop,g.dR(a.ea,!1))},l5=function(a){return a.j&&a.j.qg?a.j.qg:a.cards[0]&&a.cards[0].qg?a.cards[0].qg:null},kfb=function(a,b){return g.Bb(a.cards,function(c){return c.qg.id===b})},m5=function(a,b,c){c5.call(this,a,b);
this.annotation=c;this.isActive=!1},wfb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},n5=function(a,b,c){m5.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.j=this.J=this.D=null},xfb=function(a,b){var c=void 0===c?0:c;
var d=seb(b).width;g.xn(b,d);c=new yeb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,zeb);g.H(a,c);a.context.B.Ta(c,"begin",function(){g.Dn(b,!0)});
c.play()},Afb=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ma:["iv-branding-context-name"],Aa:b.channel_name}),d=a.createElement({G:"div",Ma:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.NU(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.I),a.j.Ja(d));var f=a.createElement({G:"div",Ma:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ma:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Dn(h,!1);var l=a.createElement({G:"div",Ma:["branding-context-container-outer"]});l.appendChild(h);g.rn(l,"right",b.image_width+"px");g.cf(a.Ab(),l);a.B=new g.lq(function(){yfb(a,h,l)},500);
g.H(a,a.B);a.context.j.Ta(a.Ab(),"mouseover",function(){zfb(a,h,l,f,b.image_height)});
a.context.j.Ta(a.Ab(),"mouseout",function(){a.B.start()})}},zfb=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Cn(b);a.j||(b.style.width=g.wn(f.width,!0),c.style.width=g.wn(f.width,!0));g.rn(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.rn(d,"right","1px");a.C=!0;g.Dn(b,!0);a.D=new g.lq(function(){g.tq(this.Ab(),"iv-branding-active")},0,a);
a.D.start()}},yfb=function(a,b,c){g.vq(a.Ab(),"iv-branding-active");
a.J=new g.lq(function(){g.Dn(b,!1);a.j||(c.style.width=g.wn(0,!0))},250);
a.J.start();a.C=!1},Bfb=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Z=c;this.videoData=d;this.logger=e;this.I=f;this.u=h},Cfb=function(a,b,c){m5.call(this,a,b,c);
var d=this;this.V=this.isCollapsed=this.ea=!1;this.J=5E3;this.u=this.B=this.j=this.C=null;this.K=this.createElement({G:"div",Ma:["iv-promo-contents"]});this.D=new g.lq(function(){d.j.setAttribute("aria-hidden","true");g.Dn(d.B,!1);g.Dn(d.u,!0)},700,this);
g.H(this,this.D)},Efb=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.Ab().setAttribute("aria-hidden","true");a.Ab().setAttribute("aria-label","Promotion");a.Ab().tabIndex=0;var e=a.annotation.jf(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ma:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({G:"span",S:"iv-promo-video-duration",Aa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",S:"iv-promo-playlist-length",Aa:b.playlist_length.toString()}),h.appendChild(f));e&&d5(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",S:"iv-promo-txt"}),g.pe(f,Y4(e)),a.j=f):a.j=a.createElement({G:"div",S:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",X:[{G:"strong",Aa:b.text_line_1}]});
var m=a.createElement({G:"p",X:[{G:"span",S:"iv-promo-link",Aa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ma:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ma:["iv-button","iv-promo-button"],X:[{G:"span",S:"iv-button-content",Aa:f}]});var p=a.createElement({G:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&d5(a,a.Ab(),e,a.annotation.id,b.session_data,void 0,c)}g.tq(a.j,"iv-click-target");
e&&d5(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",X:[{G:"span",Aa:b.text_line_1}]}),m=a.createElement({G:"p",X:[{G:"strong",Aa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ma:["yt-badge","iv-promo-badge-live"],Aa:"LIVE NOW"})),g.tq(a.j,"iv-click-target"),e&&d5(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.K.appendChild(a.j);p&&a.K.appendChild(p);
c=a.createElement({G:"div",S:"iv-promo-actions"});a.u=a.createElement({G:"button",Ma:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Ta(a.u,"click",function(q){Dfb(a,5E3,q)});
c.appendChild(a.u);g.Dn(a.u,!1);a.context.j.Ta(a.Ab(),"mouseover",a.P4,a);a.context.j.Ta(a.Ab(),"mouseout",a.O4,a);a.context.j.Ta(a.Ab(),"touchend",function(q){Dfb(a,5E3,q)});
a.B=a.createElement({G:"button",Ma:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Ta(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.K4:a.J4,a);c.appendChild(a.B);g.uq(a.Ab(),d);h&&(g.cf(a.Ab(),h),n&&h.appendChild(n));g.cf(a.Ab(),a.K);g.cf(a.Ab(),c)},Dfb=function(a,b,c){c.stopPropagation();
Ffb(a);Gfb(a,b);a.j.focus()},Hfb=function(a){a.isCollapsed||a.V||a.C||(g.tq(a.Ab(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},Ffb=function(a){a.D.stop();
a.isCollapsed&&(g.wq(a.Ab(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Dn(a.u,!1),g.Dn(a.B,!0))},Gfb=function(a,b){a.C||(a.C=g.Tf(function(){Ifb(this);
Hfb(this)},b,a))},Ifb=function(a){a.C&&(g.Ma.clearTimeout(a.C),a.C=null)},Jfb=function(a){this.I=a},mfb=function(a,b,c){b&&(c?o5(a,b.map(function(d){return g.aq(d,c)})):o5(a,b))},o5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.v(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.RC(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},Kfb=function(a){g.XT.call(this,a);
var b=this;this.ea=this.K=!1;this.loadNumber=0;this.J={};this.logger=new Jfb(this.player);this.C=new g.pK(this);this.D=this.Ww=null;this.events=new g.pK(this);this.uh=this.V=this.j=null;this.oa=[];g.H(this,this.C);this.C.T(this.player,"onVideoAreaChange",function(){b.ra("onVideoAreaChange")});
this.C.T(this.player,"onHideControls",function(){b.ra("onHideControls")});
this.C.T(this.player,"onShowControls",function(){b.ra("onShowControls")});
this.C.T(this.player,"resize",function(d){b.ra("resize",d)});
this.C.T(this.player,"presentingplayerstatechange",function(d){b.ra("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.b0,this);this.subscribe("resize",this.bI,this);this.player.W().Fa.subscribe("vast_info_card_add",this.MX,this);g.H(this,this.events);this.qa=this.createElement({G:"div",S:"video-custom-annotations"});this.u=new g.X({G:"div",Ma:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.$S(this.player,this.u.element,4);this.u.hide();this.B=new g.X({G:"div",Ma:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({G:"div",S:"video-annotations"});
a.appendChild(this.qa);this.B.element.appendChild(a);this.Nw()&&this.load();var c=this.createElement({G:"style"});(g.Oe("HEAD")[0]||document.body).appendChild(c);g.rb(this,function(){g.jf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Lfb=function(a){a=a.createElement({G:"div",
Ma:["annotation","annotation-type-custom"]});g.Dn(a,!1);return a},Mfb=function(a,b){b=!b.isCued()&&!g.FP(b,1024);
g.dR(a.u,b);g.dR(a.B,b)},Nfb=function(a,b,c){a.K=!0;
a.D=g.Az(b,c)},Ofb=function(a,b){for(var c={},d=g.v(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Va(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Ofb(a,e))}return c},Sfb=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.W().Fa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.tz(h)&&h.responseXML?h.responseXML:null)&&Pfb(a,h)}};
g.eB()&&(d.onFinish=Qfb(a,d.onFinish));d.postParams={ic_only:"1"};Rfb(d,c);a.K=!0;g.Az(b.Va,d)}}},Rfb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.KB&&(a.postParams.ic_coll=b.KB);b.HL&&(a.postParams.ic_xml=b.HL);b.qJ&&(a.postParams.ic_track=b.qJ)},Tfb=function(a){var b=new g.X({G:"div"});
g.Dn(b.element,!1);var c=new hfb(a.player,b.element,p5(a));g.H(c,b);b.Ja(a.u.element);c.GE();return c},p5=function(a){if(!a.V){var b=new Beb(a);
g.H(a,b);var c=new g.El(a);g.H(a,c);a.V=new Bfb(b,c,a.player.W(),a.player.getVideoData(),a.logger,a.player,a.nj)}return a.V},Pfb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.NG();if(e){var f=g.MG();f&&g.fz(g.qBa)(void 0,e,f,[g.KG(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Ofb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=X4(f.type,Ufb),p=X4(f.style,Vfb),q=Reb(f.data),r=0!==q.length?JSON.parse(q):{};var u=f.action;f=Xeb;if(null==u)var y=null;else if(g.Ta(u)){l=[];for(var A=g.v(u),F=A.next();!F.done;F=A.next()){var M=f(F.value);
M&&l.push(M)}y=l}else{var K=f(u);y=K?[K]:[]}e=m&&n?new Yeb(m,n,p,y,r):null}else e=null}catch(oa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=Lfb(f),T=null;switch(l.type){case "branding":if(f.player.W().Hd)break;f.u.element.appendChild(G);T=new n5(G,p5(f),l);break;case "promotion":g.$S(f.player,G,4),T=new Cfb(G,p5(f),l)}T&&T.GE();if(f=T)g.H(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Tfb(a),g.H(a,a.j));if("card"===e.type){c=a.j;var Z=e&&e.data&&e.data.card_type;
f=e.data;if(Z)switch(l=f.tracking||{},l={SV:l.impression,click:l.click,close:l.close,qZ:l.teaser_impression,nJ:l.teaser_click},G=f.tracking_params||{},T=null,Z){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,Qo:G.card?g.KG(G.card):null,zl:G.teaser?g.KG(G.teaser):null,xg:G.icon?g.KG(G.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,eY:f.image_url,title:f.title,metaInfo:f.meta_info,url:Z4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};h5(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,Qo:G.card?g.KG(G.card):null,zl:G.teaser?
g.KG(G.teaser):null,xg:G.icon?g.KG(G.icon):null,RE:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:Z4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};h5(c,e);break;case "productListing":f.signin_url&&(T=Z4({target:"current",value:f.signin_url}));Z=[];for(var ka=f.offers||[],ua=0;ua<ka.length;ua++)Z.push(new dfb(g.Ge(ka[ua].merchant),g.Ge(ka[ua].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,Qo:G.card?g.KG(G.card):null,zl:G.teaser?g.KG(G.teaser):null,xg:G.icon?g.KG(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,IB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:Z4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Obb:T,Nbb:f.signin_title?f.signin_title:void 0,Mbb:f.signin_message?f.signin_message:void 0,offers:Z,onClickCommand:null};h5(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,Qo:G.card?g.KG(G.card):
null,zl:G.teaser?g.KG(G.teaser):null,xg:G.icon?g.KG(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,IB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:Z4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};h5(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,Qo:G.card?g.KG(G.card):null,zl:G.teaser?g.KG(G.teaser):null,xg:G.icon?g.KG(G.icon):null,RE:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:Z4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},h5(c,e)}}else ifb(a.j,e);c=!0}}c&&
(I4(a.player),a.bI())},Wfb=function(a,b){var c=!1;
a.j||(a.j=Tfb(a),g.H(a,a.j));for(var d=g.v(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(jfb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.QO(f)||(c=a.j,d=b.headerText?g.pG(b.headerText):"",g.mf(c.Zb,d),c.V&&c.V.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.KG(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.KG(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.xg=b.icon.infoCardIconRenderer.trackingParams?g.KG(b.icon.infoCardIconRenderer.trackingParams):null,a.bI());I4(a.player)}},Xfb=function(a,b,c,d,e){if(!a.player.W().Hd){var f=[];
b.navigationEndpoint&&g.S(b.navigationEndpoint,g.B3)&&g.S(b.navigationEndpoint,g.B3).browseId&&f.push(new Ueb("openUrl","click",new Seb("/channel/"+g.S(b.navigationEndpoint,g.B3).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.S(b.subscribeButton,
g.JO)){d.channel_id=g.S(b.subscribeButton,g.JO).channelId;var l;b=g.S(b.subscribeButton,g.JO);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.pG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.pG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.pG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.pG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.S(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.C3))?void 0:m.url)||"";l={subscribeText:g.pG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.pG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Yeb(c,"branding","branding",f,d);l=Lfb(a);a.u.element.appendChild(l);f=new n5(l,p5(a),f);f.GE();g.H(f,f);a.J[c]=f}},Qfb=function(a,b){return function(){var c=g.Fa.apply(0,arguments);
a.isDisposed()||a.oa.push(g.dq.Ji(function(){b.apply(null,g.pa(c))}))}},Yfb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.SS.prototype.mA=g.da(19,function(a,b){var c=g.sU(this.Eb());c&&c.mA(a,b)});
var K4={},L4=null;g.eb(N4,g.Fq);g.k=N4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.qd())return!1;M4(this);this.startTime=a=g.cb();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.RH();this.Xl("play");-1==this.j&&this.Xl("resume");this.j=1;var b=g.Ya(this);b in K4||(K4[b]=this);ueb();veb(this,a);return!0};
g.k.stop=function(a){M4(this);this.j=0;a&&(this.progress=1);web(this,this.progress);this.Xl("stop");this.ir()};
g.k.pause=function(){this.qd()&&(M4(this),this.j=-1,this.Xl("pause"))};
g.k.xa=function(){0==this.j||this.stop(!1);this.Xl("destroy");N4.Sf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.ZJ=function(){this.Xl("animate")};
g.k.Xl=function(a){this.dispatchEvent(new xeb(a,this))};
g.eb(xeb,g.ub);g.eb(O4,N4);O4.prototype.B=function(){};
O4.prototype.ZJ=function(){this.B();O4.Sf.ZJ.call(this)};
O4.prototype.ir=function(){this.B();O4.Sf.ir.call(this)};
O4.prototype.RH=function(){this.B();O4.Sf.RH.call(this)};
g.eb(yeb,O4);yeb.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(Beb,g.D);g.k=Beb.prototype;g.k.Ta=function(a,b,c,d){c=(0,g.$a)(c,d||this.u);a=g.yA(a,b,c);this.j.push(a);return a};
g.k.uH=function(a,b,c,d){c=(0,g.$a)(c,d||this.u);a=g.rna(a,b,c);this.j.push(a);return a};
g.k.Kc=function(a){g.zA(a);g.Hb(this.j,a)};
g.k.Rf=function(){g.zA(this.j);this.j.length=0};
g.k.xa=function(){this.Rf();g.D.prototype.xa.call(this)};g.w(Eeb,g.XT);g.k=Eeb.prototype;g.k.load=function(){g.XT.prototype.load.call(this);if(!R4(this)){var a=g.iza(this.player.getVideoData());a?(a=Deb(a,Feb(this)),S4(this,a,!1)):Geb(this)}};
g.k.unload=function(){S4(this,null);this.B&&(this.B.abort(),this.B=null);g.XT.prototype.unload.call(this)};
g.k.Hh=function(a,b){return R4(this)?"loadCustomEndscreenRenderer"===a?(a=Deb(b,"new"),S4(this,a),!0):null:null};
g.k.getOptions=function(){return R4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Kb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Zfb.length;f++){var h=Math.abs(b.width-Zfb[f]);if(-1===e||d>=h)e=f,d=h}d=$fb[e];this.u&&g.rn(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Bn(e.element,m,f);g.xn(e.element,n,p);g.wq(e.element,agb);256<m||256<f?g.tq(e.element,"ytp-ce-large-round"):96<m||96<f?g.tq(e.element,"ytp-ce-medium-round"):g.tq(e.element,"ytp-ce-small-round");g.wq(e.element,bgb);m=h.left+h.width/2;h=h.top+l/2;g.tq(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.wq(e.element,$fb);g.tq(e.element,d);(e=g.Pe(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.rn(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())W4(this,this.endscreen.impressionUrls),(a=g.NG())&&this.endscreen.visualElement&&g.rQ(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.tq(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.tq(b,"ytp-ce-shown");W4(this,c.impressionUrls);(b=g.NG())&&g.rQ(b,c.visualElement);this.player.W().J&&this.player.Qa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.vq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.vq(b,"ytp-ce-shown");this.player.W().J&&this.player.Qa("endscreenelementhidden",a)}};
g.k.W8=function(a){var b=this;a.target===window&&(new g.lq(function(){for(var c=g.v(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.wq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Zfb=[346,426,470,506,570,640,853,1280,1920],$fb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),bgb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],agb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Teb={Ioa:"current",NNa:"new"};var Veb={CLOSE:"close",nRa:"openUrl",SUBSCRIBE:"subscribe"},Web={nna:"click",CLOSE:"close",yza:"hidden",cWa:"rollOut",dWa:"rollOver",zXa:"shown"};Yeb.prototype.jf=function(){var a=Zeb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Vfb={uia:"anchored",t_:"branding",CHANNEL:"channel",yoa:"cta",Cza:"highlightText",ADa:"label",PLAYLIST:"playlist",HTa:"popup",h_a:"speech",SUBSCRIBE:"subscribe",j2a:"title",VIDEO:"video",e8a:"website"},Ufb={t_:"branding",ila:"card",Fqa:"drawer",Bza:"highlight",yJa:"marker",XUa:"promotion",TEXT:"text",C9a:"widget"};g.w(c5,g.D);g.k=c5.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.hG(a,b,{id:c,namespace:"annotations_module"});d&&this.fb.set(a,d);e&&this.kb.set(a,e);this.context.I.gf([a])};
g.k.GE=function(){this.context.u.subscribe("resize",this.PF,this)};
g.k.Ab=function(){return this.element};
g.k.aK=function(a,b,c,d,e,f){if(this.xb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.jf(this.Ab())};
g.k.PF=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=Y4(a);if(f){var h=ffb(f,a.target),l=function(){a.j&&e.context.I.pauseVideo();var m=e.context.videoData.Ed||!1,n=g.lz(f||"");m&&n&&(n.v||n.list)?e.context.I.po(n.v,b,n.list,!1):g.zP(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);o5(this.context.logger,c,l,d);efb(f)||(c=g.NG(),d=b.itct,c&&d&&g.uQ(c,g.KG(d)))}};
g.k.xa=function(){this.fb.clear();this.kb.clear();g.D.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.H(this,a);return a.element};g.w(hfb,c5);g.k=hfb.prototype;g.k.qt=function(){this.qa&&h5(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.Cn(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.PF=function(){var a=this.isAvailable();g.Dn(this.Ab(),a);g.xq(this.context.I.getRootNode(),g.AX.IV_DRAWER_ENABLED,a);I4(this.I)};
g.k.destroy=function(){this.I.mA(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.iD(this.oa);g.GA(this.Va);this.Ya&&this.Ya.dispose();this.D&&this.D.dispose();c5.prototype.destroy.call(this)};
g.k.B3=function(){if(this.B){o5(this.context.logger,l5(this).bj.close);var a=g.NG();a&&this.K&&g.uQ(a,this.K);g5(this)}};
g.k.T3=function(){g.xq(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.I5=function(){var a=g.NG(),b=l5(this);b=b?b.xg:this.xg;a&&b&&g.sQ(a,[b])};
g.k.H5=function(){var a=g.NG(),b=l5(this);b=b?b.xg:this.xg;a&&b&&g.tQ(a,[b])};
g.k.Z_=function(){var a=l5(this);o5(this.context.logger,a.bj.qZ);var b=g.NG();b&&a&&g.sQ(b,[a.zl,a.xg])};
g.k.J5=function(){var a=g.NG(),b=l5(this);a&&b&&g.tQ(a,[b.zl])};
g.k.Y_=function(a){var b=l5(this),c=g.NG();this.j?a?(a=this.context.logger,o5(a,b.bj.nJ),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.zl&&g.uQ(c,b.zl)):(a=this.context.logger,o5(a,b.bj.nJ),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.xg&&g.uQ(c,b.xg)):(a=this.context.logger,o5(a,b.bj.nJ),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.xg&&g.uQ(c,this.xg))};g.w(m5,c5);m5.prototype.GE=function(){c5.prototype.GE.call(this);wfb(this)};
m5.prototype.show=function(){c5.prototype.show.call(this);var a=g.NG(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.sQ(a,[g.KG(b.itct)])};
m5.prototype.hide=function(){c5.prototype.hide.call(this);var a=g.NG(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.tQ(a,[g.KG(b.itct)])};g.w(n5,m5);
n5.prototype.show=function(){if(!this.isActive){m5.prototype.show.call(this);if(!this.K){g.tq(this.Ab(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ma:["branding-img","iv-click-target"],Y:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Dn(this.u,!1);var b=this.createElement({G:"button",Ma:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.Ab().appendChild(b);var c=this.annotation.jf();c&&d5(this,b,
c,this.annotation.id,a.session_data);Afb(this,a);this.K=!0}g.Dn(this.Ab(),!0);this.isActive=!0;this.u&&(xfb(this,this.u),g.tq(this.context.I.getRootNode(),"ytp-branding-shown"))}};
n5.prototype.hide=function(){this.isActive&&(m5.prototype.hide.call(this),g.Dn(this.Ab(),!1),this.isActive=!1,g.vq(this.context.I.getRootNode(),"ytp-branding-shown"))};
n5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);m5.prototype.destroy.call(this)};g.w(Cfb,m5);g.k=Cfb.prototype;g.k.show=function(){this.isActive||(m5.prototype.show.call(this),this.ea||(Efb(this),this.ea=!0),g.Dn(this.Ab(),!0),g.Tf(function(){g.vq(this.Ab(),"iv-promo-inactive")},100,this),this.Ab().removeAttribute("aria-hidden"),this.isActive=!0,Ifb(this),Ffb(this),Gfb(this,this.J))};
g.k.hide=function(){this.isActive&&(g.tq(this.Ab(),"iv-promo-inactive"),this.isActive=!1,this.Ab().setAttribute("aria-hidden","true"))};
g.k.aK=function(a,b,c,d,e,f){return this.isCollapsed?!1:m5.prototype.aK.call(this,a,b,c,d,e,f)};
g.k.P4=function(a){this.V=!0;Dfb(this,500,a)};
g.k.O4=function(){this.V=!1;Hfb(this)};
g.k.J4=function(a){a.stopPropagation();this.hide()};
g.k.K4=function(a){a.stopPropagation();Ifb(this);this.isCollapsed=!0;g.tq(this.Ab(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();m5.prototype.destroy.call(this)};g.w(Kfb,g.XT);g.k=Kfb.prototype;g.k.Hh=function(a,b){if(!Yfb(this.player.W().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.G9a(b))&&Pfb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(lfb(this.j,b),I4(this.player)),!0}return null};
g.k.getOptions=function(){return Yfb(this.player.W().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Nw=function(){var a=this.player.W(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.Ed&&a.oa||g.MS(this.player.app)?!1:1===c&&!b.gT||a.Fa.get(b.videoId)||g.RO(b)||g.jza(b)?!0:!1};
g.k.bI=function(){if(this.B){var a=this.player.qb().getVideoContentRect(!0);g.Bn(this.B.element,a.width,a.height);g.xn(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Rk();a=this.j;b=b.width;g.xq(a.C,"iv-drawer-small",426>=b);g.xq(a.C,"iv-drawer-big",1280<=b)}};
g.k.b0=function(a){Mfb(this,a.state);g.FP(a.state,2)&&(this.Ik()&&this.Po()&&2!==this.player.getPresentingPlayerType()&&this.nA(!1),this.mA(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.tz(h)&&h.responseXML?h.responseXML:null)&&(Pfb(b,h),g.tq(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.XT.prototype.load.call(this);Mfb(this,this.player.Nb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.eB()&&(a=Qfb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.W().Fa.get(d);f&&Rfb(e,f);f=f&&(f.HL||f.KB);if(!c.kx||f)c.Va?Nfb(this,c.Va,e):(this.Ww=function(){if(!b.K)b.onVideoDataChange(e);var h=b.player.getVideoData();if((null==h?0:g.QO(h))&&!b.ea){var l,m;if(h=null==(l=h.zd)?void 0:null==(m=l.cards)?void 0:m.cardCollectionRenderer)b.ea=!0,Wfb(b,h),h.headerText&&b.uh&&(l=g.pG(h.headerText),b.uh.setAttribute("title",l))}},this.player.addEventListener("videodatachange",
this.Ww));
g.$S(this.player,this.B.element,4);this.bI();(f=g.RO(c))&&Wfb(this,f);(f=g.jza(c))&&f.featuredChannel&&Xfb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.uh=g.Re("ytp-cards-button",this.player.getRootNode())};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&Nfb(this,b.Va,a)};
g.k.unload=function(){this.player.Ie("annotations_module");for(var a=g.v(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.V=null;this.j&&(this.j.destroy(),this.j=null,I4(this.player));this.K=!1;this.D&&(this.D.abort(),this.D=null);this.ea=!1;this.J={};this.u.hide();g.XT.prototype.unload.call(this);this.B.detach();this.Ww&&(this.player.removeEventListener("videodatachange",this.Ww),this.Ww=null)};
g.k.MX=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Sfb(this):this.load())};
g.k.Ik=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ea};
g.k.Po=function(){return!!this.j&&this.j.B};
g.k.nA=function(a,b,c){b=void 0===b?!1:b;this.Ik();this.j&&(a?c?f5(this.j,c,b):f5(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):g5(this.j))};
g.k.mA=function(a,b){this.player.ra(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.W().Fa.unsubscribe("vast_info_card_add",this.MX,this);g.vq(this.player.getRootNode(),g.AX.IV_DRAWER_OPEN);for(var a=this.oa,b=g.dq,c=0,d=a.length;c<d;c++)b.Sj(a[c]);this.oa.length=0;g.XT.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.H(this,a);return a.element};g.WT("annotations_module",Kfb);g.WT("creatorendscreen",Eeb);})(_yt_player);
