// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmDexglVGDiUJLs9HXXO7h_Ewqw3qZLUY',
    appId: '1:833111296431:web:9cb4da627514ba4786075a',
    messagingSenderId: '833111296431',
    projectId: 'spider-dreams',
    authDomain: 'spider-dreams.firebaseapp.com',
    storageBucket: 'spider-dreams.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD05C48gyW9qwW2YHN2PaIqLrtMDrZSXw',
    appId: '1:833111296431:android:1e4e5b63403890e086075a',
    messagingSenderId: '833111296431',
    projectId: 'spider-dreams',
    storageBucket: 'spider-dreams.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiPWVzQowtAJ8g5UmyRiVJqFbgkWohUSY',
    appId: '1:833111296431:ios:4057ad27a1cf0e5586075a',
    messagingSenderId: '833111296431',
    projectId: 'spider-dreams',
    storageBucket: 'spider-dreams.appspot.com',
    androidClientId: '833111296431-0mv22pj55l5pfqbvohrkdin4ml1sufdv.apps.googleusercontent.com',
    iosClientId: '833111296431-h6nsa44a606n36icsin8at58qtckkp9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.spiderDream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiPWVzQowtAJ8g5UmyRiVJqFbgkWohUSY',
    appId: '1:833111296431:ios:4057ad27a1cf0e5586075a',
    messagingSenderId: '833111296431',
    projectId: 'spider-dreams',
    storageBucket: 'spider-dreams.appspot.com',
    androidClientId: '833111296431-0mv22pj55l5pfqbvohrkdin4ml1sufdv.apps.googleusercontent.com',
    iosClientId: '833111296431-h6nsa44a606n36icsin8at58qtckkp9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.spiderDream',
  );
}
